---
title: "zx24_40ov_analysis"
author: "Yulong Liu (adopted from Seurat offical Vignettes)"
date: "0/30/2019"
output: html_notebook
---

This analysis is based on official vignettes from Seurat (https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html Compiled: October 08, 2019). 

```{r setup, include=FALSE,cache=FALSE}
library(Seurat)
library(dplyr)
library(Matrix)
library(future)

# Function to search gene names 
hFind <- function (x) {
  zx24_40ov@assays$RNA@data@Dimnames[[1]][grep(x,zx24_40ov@assays$RNA@data@Dimnames[[1]],ignore.case = T)]
}

# Function to obtain raw gene expression info
infoRGE <- function (x) {
# info Raw Gene Expression
  RawExp<-FetchData(object = zx24_40ov, vars = x, slot = "counts")
  NonZero <-apply(FetchData(object = zx24_40ov, vars = x, slot = "counts"),1, function(row) all(row !=0 ))
  print("1.gene expression table count  2.number of expressed cells  3.average exp")
  # Expression count table
  b <- table (RawExp[NonZero,])
  # Total number of non zero cells
  c <- length(RawExp[NonZero,])
  # Average gene exp
  d<- mean(RawExp[NonZero,])
  return (list(b,c,d))
}
  
```


### Combine somatic cell libraries 
```{r combine, cache=TRUE}
# Load the two somatic cell libraries and merge
load(file = "zx2_40ov_clean_orig.robj")
load(file = "zx4_40ov_clean_orig.robj")
zx24_40ov <- merge(x=zx2_40ov_clean_orig,y=zx4_40ov_clean_orig)

# Check the total number of libraries
unique(zx24_40ov@meta.data$orig.ident)

rm(zx2_40ov_clean_orig)
rm(zx4_40ov_clean_orig)

```


```{r sctransform_initial, warning=FALSE}
# We decided to use SCTransform as our final analysis normalization method based on Hafemeister et al., 2019 on bioRxive. This method uses regularized negative binomial regression to normalize the data, which demonstrated to improve the removal of molecular count influence.
zx24_40ov <- SCTransform(zx24_40ov, verbose = FALSE)

```


```{r pca_and_heatmap_initial, fig.height=20,fig.width=10}
# Use variable genes to find PCs
zx24_40ov <- RunPCA(zx24_40ov, features = VariableFeatures(object = zx24_40ov))

# Plot heatmaps based on PCs
DimHeatmap(zx24_40ov, dims = 1:20, cells = 500, balanced = TRUE)

```


```{r elbow_plot_inital, fig.height=6, fig.width=15, warning=FALSE}
# Elbow plot and jackstraw plots are used to determine the number of PC to use
ElbowPlot(zx24_40ov,ndims = 50)

```

```{r JackStraw_initial, fig.height=6, fig.width=15, warning=FALSE}
# Elbow plot and jackstraw plots are used to determine the number of PC to use 
plan("multiprocess", workers = 4)
zx24_40ov <- JackStraw(zx24_40ov, num.replicate = 100,dims = 50)
zx24_40ov <- ScoreJackStraw(zx24_40ov, dims = 1:50)
JackStrawPlot(zx24_40ov, dims = 1:50)
plan("sequential")

```


```{r cluster_and_UMAP_inital, fig.height=5, fig.width=7}

# We choose 17 PCs for our final analysis based on the sharp drop of p-values at 17 PCs in the Jack Straw plot, and the UMAP plot made the most sense to us based on biological knowledge. 
zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:17)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:17)
DimPlot(zx24_40ov, label = T)

```

```{r remove_residual_blood_cells}
# Blood cell marker
FeaturePlot(zx24_40ov,"hbaa1")

# Remove the residual blood cell cluster
zx24_40ov <- subset(zx24_40ov,idents = 15, invert= T )

```


### Final Clustering
```{r sctransform_final, warning=FALSE}
zx24_40ov <- SCTransform(zx24_40ov, verbose = FALSE)

```

```{r pca_and_heatmap_final, fig.height=20,fig.width=10}
# Use variable genes to find PCs
zx24_40ov <- RunPCA(zx24_40ov, features = VariableFeatures(object = zx24_40ov))

# Plot heatmaps based on PCs
DimHeatmap(zx24_40ov, dims = 1:20, cells = 500, balanced = TRUE)

```

```{r elbow_plot_final, fig.height=6, fig.width=15, warning=FALSE}
# Elbow plot and jackstraw plots are used to determine the number of PC to use
ElbowPlot(zx24_40ov,ndims = 50)

```

```{r JackStraw_final, fig.height=6, fig.width=15, warning=FALSE}
# Elbow plot and jackstraw plots are used to determine the number of PC to use 
plan("multiprocess", workers = 4)
zx24_40ov <- JackStraw(zx24_40ov, num.replicate = 100,dims = 50)
zx24_40ov <- ScoreJackStraw(zx24_40ov, dims = 1:50)
JackStrawPlot(zx24_40ov, dims = 1:50)
plan("sequential")

```

```{r cluster_and_UMAP_final, fig.height=5, fig.width=7}
# Due to the complex nature of data including multiple cell types, we tested a spectrum of the PCs for both clustering and UMAP. Take elbow plot, Jack Straw plot, and biological knowledge into consideration when choosing  the PC numbers. 
zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:16)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:16)
DimPlot(zx24_40ov, label = T)

zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:20)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:20)
DimPlot(zx24_40ov, label = T)

zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:25)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:25)
DimPlot(zx24_40ov, label = T)

zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:30)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:30)
DimPlot(zx24_40ov, label = T)

zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:40)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:40)
DimPlot(zx24_40ov, label = T)

# We choose 20 PCs for our final analysis based on the elbow curve ends around 20 PCs, and the UMAP plot made the most sense to us based on biological knowledge. 
zx24_40ov <- FindNeighbors(zx24_40ov, dims = 1:20)
zx24_40ov <- FindClusters(zx24_40ov, resolution = 0.5)
zx24_40ov <- RunUMAP(zx24_40ov, dims = 1:20)
DimPlot(zx24_40ov, label = T)

```


```{r markerplots, fig.height=15, fig.width=20}
# Cell type identification
FeaturePlot(object = zx24_40ov, c("col1a1a", "cyp17a1", "fli1a", "lyz", "lck","mpeg1.1","gsdf", "lhx9","gpc1a","cx34.5","pcna","cxcl12a", "scara3","fgf24","en1b","tbx2b"), cols = c("grey90", "blue"), pt.size = 0.5)

```


```{r save_file_final}
zx24_40ov_final <- zx24_40ov
save(zx24_40ov_final, file = "zx24_40ov_final.robj") 

```


```{r session_info}
sessionInfo()

```
